name: dart_rss
version: 2.0.1
description: dart_rss is a rss parser for RSS1.0/RSS2.0/Atom. It also support Dublin-Core, Content, Syndication additional modules. This libary is forked from webfeed(https://github.com/witochandra/webfeed).
homepage: https://github.com/anhtuan23/dart_rss
environment:
  sdk: ^3.0.0
dependencies:
  xml: ^7.0.1
  http: ^1.6.0
  intl: ^0.20.2

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.1
